apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pull-display
spec:
  params:
    - name: gitrepourl
      description: The git repo to clone.
      default: Some message.
      type: string
  workspaces:
  - name: source
  steps:
  - name: read
    image: alpine/git:latest
    workingDir: $(workspaces.source.path)
    script: | 
      #!/usr/bin/env sh
      export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      git clone $(params.gitrepourl)
      ls -ltra 