- name: fluent-bit
  image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.32.4
  imagePullPolicy: Always
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 100Mi
  volumeMounts:
    - name: varlog
      mountPath: /var/log
      readOnly: true
    - name: fluent-bit-config
      mountPath: /fluent-bit/etc/

- name: varlog
  hostPath:
    path: /var/log
- name: fluent-bit-config
  configMap:
    name: app-fluent-bit-config

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                     5
        Grace                     30
        Log_Level                 info
        Daemon                    off
        Parsers_File             parsers.conf
        HTTP_Server              On
        HTTP_Listen              0.0.0.0
        HTTP_Port                2020
        storage.path             /var/fluent-bit/state/flb-storage/
        storage.sync             normal
        storage.checksum         off
        storage.backlog.mem_limit 5M

    @INCLUDE application-log.conf

  application-log.conf: |
    [INPUT]
        Name                tail
        Tag                 application.*
        Path                /var/log/containers/hscam-agreement-add-service-deployment*.log
        Docker_Mode         On
        Docker_Mode_Flush   5
        Docker_Mode_Parser  container_firstline
        Parser              docker
        DB                  /var/fluent-bit/state/flb_container.db
        Mem_Buf_Limit       50MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Rotate_Wait         30
        storage.type        filesystem
        Read_from_Head      true

    [FILTER]
        Name                kubernetes
        Match               application.*
        Kube_URL           https://kubernetes.default.svc:443
        Kube_Tag_Prefix    application.var.log.containers.
        Merge_Log          On
        Merge_Log_Key      log_processed
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off
        Annotations        Off

    [OUTPUT]
        Name                cloudwatch
        Match               application.*
        region              ${AWS_REGION}
        log_group_name      /aws/eks/container-logs/hscam-agreement-add-service-deployment
        log_stream_prefix   hscam-agreement-add-service-deployment
        auto_create_group   true

  parsers.conf: |
    [PARSER]
        Name                docker
        Format              json
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%LZ

    [PARSER]
        Name                container_firstline
        Format              regex
        Regex               (?<log>(?<="log":")\S(?!\.).*?)(?<!\\)".*(?<stream>(?<="stream":").*?)".*(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}\.\w*).*(?=})
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%LZ